// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsADjT0FMyvgwx6-qwjZrPxMwuLDPNCCM',
    appId: '1:217297623709:android:793f71340bd08c0b021274',
    messagingSenderId: '217297623709',
    projectId: 'foodbnb-10778',
    storageBucket: 'foodbnb-10778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTc_2hTA-eAkkM6Q8NXJqNhFwMUy4iIY',
    appId: '1:217297623709:ios:8359eca1e3a289f1021274',
    messagingSenderId: '217297623709',
    projectId: 'foodbnb-10778',
    storageBucket: 'foodbnb-10778.firebasestorage.app',
    androidClientId: '217297623709-4m4ujsauqeav4pafadjegh8l8v49hj12.apps.googleusercontent.com',
    iosClientId: '217297623709-15d60m904ctr7kotlcpi5r0p20hvb6p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.partnerFoodbnb',
  );

}